### ISSUE TITLE
Cant install.

### ISSUE THREAD

**Issue by mixMugz** [ogom/redmine_sidekiq#12]
> bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Sidekiq::Extensions::ActiveRecord
/opt/redmine-3.3.3/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:19:in `<class:Configure>'
/opt/redmine-3.3.3/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:4:in `<module:RedmineSidekiq>'
/opt/redmine-3.3.3/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:3:in `<top (required)>'
/opt/redmine-3.3.3/plugins/redmine_sidekiq/init.rb:1:in `<top (required)>'
/opt/redmine-3.3.3/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine-3.3.3/lib/redmine/plugin.rb:146:in `each'
/opt/redmine-3.3.3/lib/redmine/plugin.rb:146:in `load'
/opt/redmine-3.3.3/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.3.3/config/environment.rb:14:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/rake:23:in `load'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/rake:23:in `<main>'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by mixMugz** [comment]
Fixed
