### ISSUE TITLE
Unable to start with plugin installed

### ISSUE THREAD

**Issue by heaveaxy** [ogom/redmine_sidekiq#18]
Hello,
Following error occurs:
NameError: uninitialized constant Sidekiq::Extensions
if Sidekiq::Extensions.respond_to?(:enable_delay!)

Logfile attached.
Redmine docker version ran: redmine:5.0.4-alpine
[redmine.log](https://github.com/ogom/redmine_sidekiq/files/10802567/redmine.log)

**Comment by HighwayStar** [comment]
It caused by incompatibility with sidekiq 7.x.x, setting 
gem 'sidekiq', '~>6.0.0' 
it solves this issue, but still doesnt work when connecting to redis
```
, [2023-04-26T06:21:38.694086 #14831]  INFO -- : [3def7ee4-7ae8-4194-9338-86e0fd1fad84] Started GET "/sidekiq" for 10.0.6.6 at 2023-04-26 06:21:38 +0000
F, [2023-04-26T06:21:38.733227 #14831] FATAL -- : [3def7ee4-7ae8-4194-9338-86e0fd1fad84]   
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] NoMethodError (undefined method `first' for nil:NilClass):
[3def7ee4-7ae8-4194-9338-86e0fd1fad84]   
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/api.rb:86:in `fetch_stats!'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/api.rb:11:in `initialize'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/helpers.rb:156:in `new'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/helpers.rb:156:in `stats'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/action.rb:51:in `_erb__summary'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/action.rb:89:in `_erb'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/action.rb:55:in `erb'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web.rb:232:in `_render'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/action.rb:60:in `erb'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/application.rb:51:in `block in <class:WebApplication>'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/application.rb:296:in `instance_exec'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/application.rb:296:in `block in call'
[3def7ee4-7ae8-4194-9338-86e0fd1fad84] sidekiq (6.0.7) lib/sidekiq/web/application.rb:294:in `catch'

```
